// Regenerates supabase/seed.sql from public/assets/js/data.js -> node scripts/generate-seed.mjs
// Run after schema.sql and every ordered Supabase migration.
import { writeFileSync } from 'node:fs';
import { tutors, courses, posts, library, settings, pages } from '../public/assets/js/data.js';
const q = (v) => v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`;
const j = (v) => `${q(JSON.stringify(v))}::jsonb`;
const out = ['-- Sample content for Courssins. Generated by scripts/generate-seed.mjs. Run AFTER schema.sql and migrations. Edit content in Admin afterwards.', ''];
tutors.forEach((t, i) => out.push(`insert into public.tutors (slug, full_name, title, specialization, bio, experience, qualifications, expertise, socials, email, image_url, published, sort_order) values (${[q(t.slug), q(t.full_name), q(t.title), q(t.specialization), q(t.bio), q(t.experience), j(t.qualifications), j(t.expertise), j(t.socials), q(t.email), q(t.image_url), 'true', i + 1].join(', ')}) on conflict (slug) do nothing;`));
out.push('');
for (const c of courses) {
  out.push(`insert into public.courses (slug, title, category, icon, short_description, description, duration, price, currency, tutor_id, image_url, outcomes, requirements, faqs, assessment_info, certificate_info, featured, published, sort_order) values (${[q(c.slug), q(c.title), q(c.category), q(c.icon), q(c.short_description), q(c.description), q(c.duration), c.price, q(c.currency), `(select id from public.tutors where slug = ${q(c.tutor_slug)})`, q(c.image_url), j(c.outcomes), j(c.requirements), j(c.faqs), q(c.assessment_info), q(c.certificate_info), c.featured, 'true', c.sort_order].join(', ')}) on conflict (slug) do nothing;`);
  for (const m of c.modules) {
    const cid = `(select id from public.courses where slug = ${q(c.slug)})`;
    out.push(`insert into public.course_modules (course_id, title, summary, topics, position) select ${cid}, ${q(m.title)}, ${q(m.summary)}, ${j(m.topics)}, ${m.position} where not exists (select 1 from public.course_modules where course_id = ${cid} and position = ${m.position});`);
    m.topics.forEach((tp, k) => out.push(`insert into public.lessons (course_id, module_id, title, content, position) select ${cid}, (select id from public.course_modules where course_id = ${cid} and position = ${m.position}), ${q(tp)}, ${q('This lesson covers: ' + tp.toLowerCase() + '. Your tutor will add notes and videos from the admin panel.')}, ${m.position * 10 + k} where not exists (select 1 from public.lessons where course_id = ${cid} and title = ${q(tp)});`));
  }
}
out.push(`insert into public.course_tutors (course_id, tutor_id) select id, tutor_id from public.courses where tutor_id is not null on conflict (course_id, tutor_id) do nothing;`);
out.push('');
posts.forEach((p) => out.push(`insert into public.blog_posts (slug, title, excerpt, content, category, author, image_url, published, published_at) values (${[q(p.slug), q(p.title), q(p.excerpt), q(p.content), q(p.category), q(p.author), q(p.image_url), 'true', q(p.published_at)].join(', ')}) on conflict (slug) do nothing;`));
library.forEach((l) => out.push(`insert into public.library (title, type, description, url, access, published) select ${[q(l.title), q(l.type), q(l.description), q(l.url), q(l.access), 'true'].join(', ')} where not exists (select 1 from public.library where title = ${q(l.title)});`));
pages.forEach((p) => {
  const legalPage = ['terms-and-conditions', 'privacy-policy'].includes(p.slug);
  const conflict = legalPage ? 'on conflict (slug) do update set title = excluded.title, html = excluded.html, css = excluded.css, meta_title = excluded.meta_title, meta_description = excluded.meta_description, published = excluded.published, updated_at = now()' : 'on conflict (slug) do nothing';
  out.push(`insert into public.pages (slug, title, html, css, meta_title, meta_description, published) values (${[q(p.slug), q(p.title), q(p.html), q(p.css), q(p.title + ' | Courssins Technology Institute'), q(p.meta_description), 'true'].join(', ')}) ${conflict};`);
});
out.push('');
for (const [k, v] of Object.entries(settings)) {
  let conflict = 'on conflict (key) do nothing';
  if (k === 'site') conflict = `on conflict (key) do update set value = settings.value || jsonb_build_object('email', excluded.value->>'email', 'socials', coalesce(settings.value->'socials', '{}'::jsonb) || jsonb_build_object('instagram', excluded.value #>> '{socials,instagram}'))`;
  if (k === 'certificate') conflict = `on conflict (key) do update set value = case when settings.value ? 'signatory_name' then settings.value else settings.value || jsonb_build_object('signatory_name', excluded.value->>'signatory_name') end`;
  out.push(`insert into public.settings (key, value) values (${q(k)}, ${j(v)}) ${conflict};`);
}
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), out.join('\n') + '\n');
console.log('seed.sql written,', out.length, 'lines');
