import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const envFile = path.join(rootDir, '.env');
const targetFile = path.join(rootDir, 'public', 'assets', 'js', 'config.js');

const readDotEnv = (filePath) => {
  if (!fs.existsSync(filePath)) return {};

  return fs.readFileSync(filePath, 'utf8')
    .split(/\r?\n/)
    .reduce((acc, rawLine) => {
      const line = rawLine.trim();
      if (!line || line.startsWith('#')) return acc;

      const equalsIndex = line.indexOf('=');
      if (equalsIndex === -1) return acc;

      const key = line.slice(0, equalsIndex).trim();
      let value = line.slice(equalsIndex + 1).trim();

      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }

      acc[key] = value;
      return acc;
    }, {});
};

const fromDotEnv = readDotEnv(envFile);
const env = { ...fromDotEnv, ...process.env };

const configText = `/* Generated by scripts/link-env.mjs from the environment. */
export const CONFIG = {
  SUPABASE_URL: ${JSON.stringify(env.SUPABASE_URL || 'https://ohkrwdmiqlkjcsnzbmma.supabase.co')},
  SUPABASE_ANON_KEY: ${JSON.stringify(env.SUPABASE_ANON_KEY || 'sb_publishable_kOMD5B_3EbxoCEeSEzXAug_rUnZfQ-2')},
  SITE_URL: ${JSON.stringify(env.SITE_URL || 'https://courssin.com.ng')},
  PAYMENT_INIT_URL: ${JSON.stringify(env.PAYMENT_INIT_URL || 'https://ohkrwdmiqlkjcsnzbmma.supabase.co/functions/v1/paystack-initialize')},
};
`;

fs.writeFileSync(targetFile, configText, 'utf8');
console.log(`Linked env values into ${path.relative(rootDir, targetFile)}`);
